"""Long help texts of the commands."""

SINGLE_TEMPLATE_HELP_TEXT = (
    "Generate single template file (docx, txt, md, html, json, ...)\n"
    "\n"
    "Usage:\n"
    "\n"
    f"| {'name':<10} | {'age':<4}\n"
    "-------------------\n"
    f"| {'Abdullah':<10} | {'32':<4}\n"
    f"| {'Rawaa':<10} | {'33':<4}\n"
    f"| {'Rama':<10} | {'25':<4}\n"
    "\n"
    "Template:\n"
    "\n"
    "{% for person in data %}\n"
    "Hello my name is {{ person['name'] }}, my age is {{ person['age'] }}\n"
    "{{ page_break }}\n"
    "{% endfor %}\n"
    "\n"
    "Command:\n"
    "\n"
    "templify s \\ \n"
    "-t <your_path_to_template_file> \\ \n"
    "-d <your_path_to_data_file> \\ \n"
    "-o <your_path_to_output_directory> \n"
    "\n"
    "it will generate a single file with three pages like this:\n"
    "\n"
    "Page 1: Hello my name is Abdullah, my age is 32\n"
    "Page 2: Hello my name is Rawaa, my age is 33\n"
    "Page 3: Hello my name is Rama, my age is 25\n"
)

MULTIPLE_TEMPLATES_HELP_TEXT = (
    "Generate multiple template files (docx, txt, md, html, json, ...)\n"
    "\n"
    "Usage:\n"
    "\n"
    f"| {'name':<10} | {'age':<4}\n"
    "-------------------\n"
    f"| {'Abdullah':<10} | {'32':<4}\n"
    f"| {'Rawaa':<10} | {'33':<4}\n"
    f"| {'Rama':<10} | {'25':<4}\n"
    "\n"
    "Template: Hello my name is {{ name }}, my age is {{ age }}\n"
    "\n"
    "Command:\n"
    "\n"
    "templify m \\ \n"
    "-t <your_path_to_template_file> \\ \n"
    "-d <your_path_to_data_file> \\ \n"
    "-o <your_path_to_output_directory> \\ \n"
    "-k name --index\n"
    "\n"
    "it will generate a multiple files like this:\n"
    "\n"
    "1 - Abdullah.docx  `Hello my name is Abdullah, my age is 32`\n"
    "2 - Rawaa.docx     `Hello my name is Rawaa, my age is 33`\n"
    "3 - Rama.docx      `Hello my name is Rama, my age is 25`\n"
)
